# This is a sample deployment file for a Kubernetes application.
# It defines a deployment for an Nginx server with 4 replicas.
# The deployment is labeled with "tier: frontend" and "app: nginx".
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    tier: frontend
    app: nginx
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 4
  template:
    metadata:
      name: nginx-2
      labels:
        app: myapp
    spec:
      containers:
        - name: nginx
          image: nginx