apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-replicast
  labels:
    app: myapp
spec:
  selector:
    matchLabels:
      env: myapp
  replicas: 3
  template:
    metadata:
      name: nginx-2
      labels:
        env: myapp
    spec:
      containers:
        - name: nginx
          image: nginx